{
 "title": "Keep Systems Summary",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "APP_TYPE", "label": "Application", "query": "eth,ecdsa,core,tbtc-monitoring" }
  ]
 },
 "panels": [
  { "title": "$APP_TYPE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "APP_TYPE" },
  {
   "title": "System Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(up{instance=~\".*$APP_TYPE.*\", job=\"systems\"}, \"node\", \"$1\", \"instance\", \"(.*?\\\\..*?)\\\\..*\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace((1 - avg(irate(node_cpu_seconds_total{instance=~\".*$APP_TYPE.*\", job=\"systems\", mode=\"idle\"}[5m])) by (instance)) * 100, \"node\", \"$1\", \"instance\", \"(.*?\\\\..*?)\\\\..*\")\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\"}[5m]) + avg_over_time(node_memory_Cached_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\"}[5m]) + avg_over_time(node_memory_Buffers_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\"}[5m])) / avg_over_time(node_memory_MemTotal_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\"}[5m]))), \"node\", \"$1\", \"instance\", \"(.*?\\\\..*?)\\\\..*\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "\nlabel_replace(100 - ((node_filesystem_avail_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\",mountpoint=\"/\",fstype!=\"rootfs\"}), \"node\", \"$1\", \"instance\", \"(.*?\\\\..*?)\\\\..*\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "$APP_TYPE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "System Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(up{instance=~\".*$APP_TYPE.*\", job=\"systems\"}, \"node\", \"$1\", \"instance\", \"(.*?\\\\..*?)\\\\..*\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace((1 - avg(irate(node_cpu_seconds_total{instance=~\".*$APP_TYPE.*\", job=\"systems\", mode=\"idle\"}[5m])) by (instance)) * 100, \"node\", \"$1\", \"instance\", \"(.*?\\\\..*?)\\\\..*\")\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\"}[5m]) + avg_over_time(node_memory_Cached_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\"}[5m]) + avg_over_time(node_memory_Buffers_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\"}[5m])) / avg_over_time(node_memory_MemTotal_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\"}[5m]))), \"node\", \"$1\", \"instance\", \"(.*?\\\\..*?)\\\\..*\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "\nlabel_replace(100 - ((node_filesystem_avail_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\",mountpoint=\"/\",fstype!=\"rootfs\"}), \"node\", \"$1\", \"instance\", \"(.*?\\\\..*?)\\\\..*\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "$APP_TYPE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "System Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(up{instance=~\".*$APP_TYPE.*\", job=\"systems\"}, \"node\", \"$1\", \"instance\", \"(.*?\\\\..*?)\\\\..*\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace((1 - avg(irate(node_cpu_seconds_total{instance=~\".*$APP_TYPE.*\", job=\"systems\", mode=\"idle\"}[5m])) by (instance)) * 100, \"node\", \"$1\", \"instance\", \"(.*?\\\\..*?)\\\\..*\")\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\"}[5m]) + avg_over_time(node_memory_Cached_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\"}[5m]) + avg_over_time(node_memory_Buffers_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\"}[5m])) / avg_over_time(node_memory_MemTotal_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\"}[5m]))), \"node\", \"$1\", \"instance\", \"(.*?\\\\..*?)\\\\..*\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "\nlabel_replace(100 - ((node_filesystem_avail_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\",mountpoint=\"/\",fstype!=\"rootfs\"}), \"node\", \"$1\", \"instance\", \"(.*?\\\\..*?)\\\\..*\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "$APP_TYPE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "System Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(up{instance=~\".*$APP_TYPE.*\", job=\"systems\"}, \"node\", \"$1\", \"instance\", \"(.*?\\\\..*?)\\\\..*\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace((1 - avg(irate(node_cpu_seconds_total{instance=~\".*$APP_TYPE.*\", job=\"systems\", mode=\"idle\"}[5m])) by (instance)) * 100, \"node\", \"$1\", \"instance\", \"(.*?\\\\..*?)\\\\..*\")\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\"}[5m]) + avg_over_time(node_memory_Cached_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\"}[5m]) + avg_over_time(node_memory_Buffers_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\"}[5m])) / avg_over_time(node_memory_MemTotal_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\"}[5m]))), \"node\", \"$1\", \"instance\", \"(.*?\\\\..*?)\\\\..*\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "\nlabel_replace(100 - ((node_filesystem_avail_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\".*$APP_TYPE.*\",job=\"systems\",mountpoint=\"/\",fstype!=\"rootfs\"}), \"node\", \"$1\", \"instance\", \"(.*?\\\\..*?)\\\\..*\")",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}