{
 "title": "Keep Systems",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "system",
    "query": "label_values({job=\"systems\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"$system\",job=\"systems\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$system\",job=\"systems\",mode=\"idle\"}[5m])) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{instance=~\"$system\",job=\"systems\"}[5m]) + avg_over_time(node_memory_Cached_bytes{instance=~\"$system\",job=\"systems\"}[5m]) + avg_over_time(node_memory_Buffers_bytes{instance=~\"$system\",job=\"systems\"}[5m])) / avg_over_time(node_memory_MemTotal_bytes{instance=~\"$system\",job=\"systems\"}[5m])))"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$system\",job=\"systems\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) /            node_filesystem_size_bytes{instance=~\"$system\",job=\"systems\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$system\",job=\"systems\"}[5m])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$system\",job=\"systems\"}[5m])",
     "legendFormat": "{{device}} write"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$system\",job=\"systems\"}[5m])",
     "legendFormat": "{{device}} received"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$system\",job=\"systems\"}[5m])",
     "legendFormat": "{{device}} sent"
    }
   ]
  }
 ]
}