{
 "title": "Keep Clients",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "client",
    "query": "label_values({job=\"clients\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Client health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"$client\",job=\"clients\"}"
    }
   ]
  },
  {
   "title": "Ethereum node connectivity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_connectivity{instance=~\"$client\",job=\"clients\"}"
    }
   ]
  },
  {
   "title": "Connected peers count ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "connected_peers_count{instance=~\"$client\",job=\"clients\"}"
    }
   ]
  },
  {
   "title": "Connected bootstrap count ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "connected_bootstrap_count{instance=~\"$client\",job=\"clients\"}"
    }
   ]
  }
 ]
}