{
 "title": "Keep Clients Summary",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "REGEXP_INSTANCE_TO_NODE",
    "label": "Regexp used to transform instance label to a node name",
    "query": "(.*?\\\\..*?)\\\\..*:[0-9]{2}(.*)"
   },
   {
    "name": "REGEXP_ADDRESS_TO_ID",
    "label": "Regexp used to transform instance label to a node name",
    "query": "^0x([a-zA-Z0-9]{6}).*$"
   },
   { "name": "APP_TYPE", "query": "ecdsa,core" }
  ]
 },
 "panels": [
  {
   "title": "Operators Accounts Balances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(eth_balance{address=~\".*\"}, \"address_id\", \"$1\", \"address\", \"^0x([a-zA-Z0-9]{6}).*$\")",
     "legendFormat": "{{name}}({{address_id}})"
    }
   ]
  },
  { "title": "$APP_TYPE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "APP_TYPE" },
  {
   "title": "Client Health",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(up{job=\"clients\", instance=~\".*$APP_TYPE.*\"}, \"node\", \"$1-$2\", \"instance\", \"$REGEXP_INSTANCE_TO_NODE\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Connected Bootstraps Count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(connected_bootstrap_count{instance=~\".*$APP_TYPE.*\"}, \"node\", \"$1-$2\", \"instance\", \"$REGEXP_INSTANCE_TO_NODE\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Connected Peers History",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(connected_peers_count{instance=~\".*$APP_TYPE.*\"}, \"node\", \"$1-$2\", \"instance\", \"$REGEXP_INSTANCE_TO_NODE\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "ETH Connectivity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(eth_connectivity{job=\"clients\", instance=~\".*$APP_TYPE.*\"}, \"node\", \"$1-$2\", \"instance\", \"$REGEXP_INSTANCE_TO_NODE\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Connected Peers Count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(connected_peers_count{instance=~\".*$APP_TYPE.*\"}, \"node\", \"$1-$2\", \"instance\", \"$REGEXP_INSTANCE_TO_NODE\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "$APP_TYPE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Client Health",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(up{job=\"clients\", instance=~\".*$APP_TYPE.*\"}, \"node\", \"$1-$2\", \"instance\", \"$REGEXP_INSTANCE_TO_NODE\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Connected Bootstraps Count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(connected_bootstrap_count{instance=~\".*$APP_TYPE.*\"}, \"node\", \"$1-$2\", \"instance\", \"$REGEXP_INSTANCE_TO_NODE\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Connected Peers History",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(connected_peers_count{instance=~\".*$APP_TYPE.*\"}, \"node\", \"$1-$2\", \"instance\", \"$REGEXP_INSTANCE_TO_NODE\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "ETH Connectivity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(eth_connectivity{job=\"clients\", instance=~\".*$APP_TYPE.*\"}, \"node\", \"$1-$2\", \"instance\", \"$REGEXP_INSTANCE_TO_NODE\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Connected Peers Count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(connected_peers_count{instance=~\".*$APP_TYPE.*\"}, \"node\", \"$1-$2\", \"instance\", \"$REGEXP_INSTANCE_TO_NODE\")",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}